name: falconnect
description: A new Flutter package project.
version: 1.3.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  faltool:
    git:
      url: https://github.com/THE-EXISTING/faltool.git
      ref: 1.0.12
  falmodel:
    git:
      url: https://github.com/THE-EXISTING/falmodel.git
      ref: 1.3.0

  #PLATFORM: All
  ansicolor: ^2.0.3
  dio: ^5.7.0
  retrofit: ^4.4.1
  web_socket_channel: ^3.0.1
  connectivity_plus: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
