name: falconnect
description: A new Flutter package project.
version: 1.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  faltool:
    git:
      url: https://github.com/THE-EXISTING/faltool.git
      ref: 1.0.2
  falmodel:
    git:
      url: https://github.com/THE-EXISTING/falmodel.git
      ref: 1.1.0

  #PLATFORM: All
  ansicolor: ^2.0.2
  dio: ^5.5.0+1
  retrofit: ^4.1.0
  web_socket_channel: ^3.0.0
  connectivity_plus: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
